required = [
    "github.com/go-openapi/spec", # ASF dependency
    "github.com/gogo/protobuf/gogoproto", # required only to satisfy "dep check"
    "github.com/gogo/protobuf/protoc-gen-gogofaster",
    "github.com/gogo/protobuf/sortkeys", # required only to satisfy "dep check"
    "github.com/golang/dep/cmd/dep",
    "github.com/golang/mock/mockgen",
    "github.com/mattn/goveralls",
    "github.com/mitchellh/gox",
    "github.com/pseudomuto/protoc-gen-doc/cmd/protoc-gen-doc",
    "golang.org/x/tools/cmd/goimports",
]

[[constraint]]
  name = "github.com/coreos/etcd"
  version = "v3.3.2"

[[constraint]]
  name = "github.com/hashicorp/terraform"
  version = "0.11.11"

[[constraint]]
  name = "github.com/docker/docker"
  revision = "ac7306503d237d548e376a89ab0b899ea1a245b0"

[[constraint]]
  name = "github.com/Juniper/asf"
  branch = "proxy-fix-retry-5xx" # TODO(dfurman): change revision when merged
#  revision = "7a40ffba37b9b4180f4d3c9553c0ca5a809c2f40"
