- type: all
  template_path: pkg/client/client_grpc.go.tmpl
- type: all
  template_path: pkg/client/client_http.go.tmpl
- type: all
  template_path: vendor/github.com/Juniper/asf/pkg/db/cache/cachedb.go.tmpl
  output_dir: pkg/db/cache
- type: all
  template_path: pkg/db/db.go.tmpl
- type: all
  template_path: pkg/db/db_common.go.tmpl
- type: all
  template_path: pkg/db/db_test.go.tmpl
- type: alltype
  template_path: pkg/db/db_types.go.tmpl
- type: all
  template_path: pkg/db/etcd/etcd_notifier_service.go.tmpl
- type: alltype
  template_path: pkg/models/model.go.tmpl
- type: all
  template_path: pkg/models/type_validation.go.tmpl
- type: all
  template_path: pkg/services/base_quota_counter.go.tmpl
- type: all
  template_path: pkg/services/base_quota_getter.go.tmpl
- type: all
  template_path: pkg/services/quota_checker_service.go.tmpl
- type: all
  template_path: pkg/services/rbac_service.go.tmpl
- type: all
  template_path: pkg/services/sanitizer_service.go.tmpl
- type: all
  template_path: pkg/services/service.go.tmpl
- type: all
  template_path: pkg/services/service_common.go.tmpl
- type: all
  template_path: pkg/services/service_interface.go.tmpl
- type: all
  template_path: pkg/services/event_encoding.go.tmpl
- type: all
  template_path: pkg/services/list_response_encoding.go.tmpl
- type: all
  template_path: proto/github.com/Juniper/contrail/pkg/models/model.proto.tmpl
- type: all
  template_path: proto/github.com/Juniper/contrail/pkg/services/service.proto.tmpl
- type: all
  template_path: vendor/github.com/Juniper/asf/tools/init_psql.sql.tmpl
  output_dir: tools
- type: all
  template_path: vendor/github.com/Juniper/asf/tools/cleanup_psql.sql.tmpl
  output_dir: tools
