public_key:
  name: keypair-test
  value: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC1HchylLHeWJjF/+JqDIroY7lZzq0xDziHYJ7tCjDh+V91KvG0RsJiUa8UQxk51zNUgnBgbyuGmNGn4/if6qSS6gAuNDFYh33sFTaGMjl/MucngjSNZbEeP9HDZ4ihlc1xvgv97gC6NEoNVSfKRqsjDx8Rv8A3Btq/HRSZXcGV4PNvQ25Uxba5owVaCNrUhOejwsf6jJUb790GuAhfwAAG3oZlylflmAQ/9sQqIXZXA1vYdO8Np5L76gyQC6Bei3NzAqzt6d6JihNfcv8nLmMEkAradJgb6Fx6Zfe49dAduAB43ZB52Rfw8j34Rj8ssR4aj6rHgpyuCGDpnZ7pawQz root@992aeade58ad
aws_access_key:
aws_secret_key:

authorized_registries:
  - registry: test_registry
    username: user1
    password: password
