git fetch ansibleFetchURL
git cherry-pick ansibleCherryPickRevision
git reset --hard ansibleRevision
deployer all provision --topology /tmp/contrail_cluster/test_mc_cluster_uuid/multi-cloud/topology.yml --secret /tmp/contrail_cluster/test_mc_cluster_uuid/multi-cloud/secret.yml --tf_state /var/tmp/cloud/public_cloud_uuid/terraform.tfstate
