api_style: contrail
extends:
    - base
id: config_node
parents:
    global_system_config:
        description: 'Config node is object representing a logical node in system
            which serves config API.'
        operations: CRUD
        presence: admin-only
plural: config_nodes
prefix: /
references: {}
schema:
    properties:
        config_node_ip_address:
            $ref: types.json#/definitions/IpAddressType
            description: 'Ip address of the config node, set while provisioning.'
            operations: CRUD
            presence: admin-only
    required: []
    type: object
