---
  prefix: "/"
  api_style: "contrail"
  extends: 
    - "base"
  references: {}
  parents: 
    global_system_config: 
      operation: "CRUD"
      description: "Config node is object representing a logical node in system which serves config API."
      presence: "admin-only"
  plural: "config_nodes"
  id: "config_node"
  schema: 
    required: []
    type: "object"
    properties: 
      config_node_ip_address: 
        operations: "CRUD"
        presence: "admin-only"
        description: "Ip address of the config node, set while provisioning."
        $ref: "types.json#/definitions/IpAddressType"

