---
  prefix: "/"
  api_style: "contrail"
  extends: 
    - "base"
  references: 
    bgp_router: 
      operation: "R"
      description: "List of references to all bgp routers in systems."
      presence: "required"
  parents: 
    config_root: 
      operation: "R"
      description: "Global system config is object where all global system configuration is present."
      presence: "required"
  plural: "global_system_configs"
  id: "global_system_config"
  schema: 
    required: 
      - "autonomous_system"
    type: "object"
    properties: 
      config_version: 
        operations: "R"
        type: "string"
        description: "Version of OpenContrail software that generated this config."
        presence: "system-only"
      bgpaas_parameters: 
        operations: "CRUD"
        presence: "optional"
        description: "BGP As A Service Parameters configuration"
        $ref: "types.json#/definitions/BGPaaServiceParametersType"
      alarm_enable: 
        operations: "CRUD"
        type: "boolean"
        description: "Flag to enable/disable alarms configured under global-system-config. True, if not set."
        presence: "optional"
      mac_move_control: 
        operations: "CRUD"
        presence: "optional"
        description: "MAC move control on the network"
        $ref: "types.json#/definitions/MACMoveLimitControlType"
      plugin_tuning: 
        operations: "CRUD"
        presence: "optional"
        description: "Various Orchestration system plugin(interface) parameters, like Openstack Neutron plugin."
        $ref: "types.json#/definitions/PluginProperties"
      ibgp_auto_mesh: 
        operations: "CRUD"
        type: "boolean"
        description: "When true, system will automatically create BGP peering mesh with all control-nodes that have same BGP AS number as global AS number."
        presence: "optional"
      mac_aging_time: 
        operations: "CRUD"
        presence: "optional"
        description: "MAC aging time on the network"
        $ref: "types.json#/definitions/MACAgingTime"
      bgp_always_compare_med: 
        operations: "CRUD"
        type: "boolean"
        description: "Always compare MED even if paths are received from different ASes."
        presence: "optional"
      user_defined_log_statistics: 
        operations: "CRUD"
        collectionType: "map"
        presence: "optional"
        description: "stats name and patterns"
        $ref: "types.json#/definitions/UserDefinedLogStatList"
      graceful_restart_parameters: 
        operations: "CRUD"
        presence: "optional"
        description: "Graceful Restart parameters"
        $ref: "types.json#/definitions/GracefulRestartParametersType"
      ip_fabric_subnets: 
        operations: "CRUD"
        presence: "optional"
        description: "List of all subnets in which vrouter ip address exist. Used by Device manager to configure dynamic GRE tunnels on the SDN gateway."
        $ref: "types.json#/definitions/SubnetListType"
      autonomous_system: 
        operations: "CRUD"
        presence: "required"
        description: "16 bit BGP Autonomous System number for the cluster."
        $ref: "types.json#/definitions/AutonomousSystemType"
      mac_limit_control: 
        operations: "CRUD"
        presence: "optional"
        description: "MAC limit control on the network"
        $ref: "types.json#/definitions/MACLimitControlType"

