---
  prefix: "/"
  api_style: "contrail"
  extends: 
    - "base"
  references: {}
  parents: 
    global_system_config: 
      operation: "R"
      description: "Global vrouter config is object where all global vrouter config is present."
      presence: "required"
  plural: "global_vrouter_configs"
  id: "global_vrouter_config"
  schema: 
    required: []
    type: "object"
    properties: 
      ecmp_hashing_include_fields: 
        operation: "CRUD"
        presence: "optional"
        description: "ECMP hashing config at global level."
        $ref: "types.json#/definitions/EcmpHashingIncludeFields"
      flow_aging_timeout_list: 
        operation: "CRUD"
        presence: "optional"
        description: "Flow aging timeout per application (protocol, port) list."
        $ref: "types.json#/definitions/FlowAgingTimeoutList"
      forwarding_mode: 
        operation: "CRUD"
        presence: "optional"
        description: "Packet forwarding mode for this system L2-only, L3-only OR L2-L3. L2-L3 is default."
        $ref: "types.json#/definitions/ForwardingModeType"
      flow_export_rate: 
        operation: "CRUD"
        type: "integer"
        description: "Flow export rate is global config, rate at which each vrouter will sample and export flow records to analytics"
        presence: "optional"
      linklocal_services: 
        operation: "CRUD"
        presence: "optional"
        description: "Global services provided on link local subnet to the virtual machines."
        $ref: "types.json#/definitions/LinklocalServicesTypes"
      encapsulation_priorities: 
        operation: "CRUD"
        presence: "optional"
        description: "Ordered list of encapsulations that vrouter will use in priority order."
        $ref: "types.json#/definitions/EncapsulationPrioritiesType"
      vxlan_network_identifier_mode: 
        operation: "CRUD"
        presence: "optional"
        $ref: "types.json#/definitions/VxlanNetworkIdentifierModeType"
      enable_security_logging: 
        default: true
        operation: "CRUD"
        type: "boolean"
        description: "Enable or disable security-logging in the system"
        presence: "optional"

