api_style: contrail
extends:
    - base
id: qos_config
parents:
    global_qos_config:
        description: 'Global system QoS config for vhost and fabric traffic .'
        operations: CRUD
        presence: optional
    project:
        description: ""
        operations: 'CRUDQOS configuration specifying marking and queuing value for
            various QoS values'
        presence: optional
plural: qos_configs
prefix: /
references:
    global_system_config:
        description: 'This link is internally created and may be removed in future.
            End users should not set this link or assume it to be there'
        operations: CR
        presence: system-only
schema:
    properties:
        default_forwarding_class_id:
            $ref: types.json#/definitions/ForwardingClassId
            description: 'Default forwarding class used for all non-specified QOS
                bits'
            operations: CRUD
            presence: required
        dscp_entries:
            $ref: types.json#/definitions/QosIdForwardingClassPairs
            collectionType: map
            description: 'Map of DSCP match condition and applicable forwarding class
                for packet.'
            mapKey: key
            operations: CRUD
            presence: optional
            wrapper: true
        mpls_exp_entries:
            $ref: types.json#/definitions/QosIdForwardingClassPairs
            collectionType: map
            description: 'Map of MPLS EXP values to applicable forwarding class for
                packet.'
            mapKey: key
            operations: CRUD
            presence: optional
            wrapper: true
        qos_config_type:
            $ref: types.json#/definitions/QosConfigType
            description: 'Specifies if qos-config is for vhost, fabric or for project.'
            operations: CRUD
            presence: required
        vlan_priority_entries:
            $ref: types.json#/definitions/QosIdForwardingClassPairs
            collectionType: map
            description: 'Map of .1p priority code to applicable forwarding class
                for packet.'
            mapKey: key
            operations: CRUD
            presence: optional
            wrapper: true
    required:
        - qos_config_type
        - default_forwarding_class_id
    type: object
