---
  prefix: "/"
  api_style: "contrail"
  extends: 
    - "base"
  references: 
    global_system_config: 
      operations: "CR"
      description: "This link is internally created and may be removed in future. End users should not set this link or assume it to be there"
      presence: "system-only"
  parents: 
    project: 
      operations: "CRUDQOS configuration specifying marking and queuing value for various QoS values"
      description: ""
      presence: "optional"
    global_qos_config: 
      operations: "CRUD"
      description: "Global system QoS config for vhost and fabric traffic ."
      presence: "optional"
  plural: "qos_configs"
  id: "qos_config"
  schema: 
    required: 
      - "qos_config_type"
      - "default_forwarding_class_id"
    type: "object"
    properties: 
      qos_config_type: 
        operations: "CRUD"
        presence: "required"
        description: "Specifies if qos-config is for vhost, fabric or for project."
        $ref: "types.json#/definitions/QosConfigType"
      mpls_exp_entries: 
        operations: "CRUD"
        collectionType: "map"
        description: "Map of MPLS EXP values to applicable forwarding class for packet."
        presence: "optional"
        wrapper: true
        mapKey: "key"
        $ref: "types.json#/definitions/QosIdForwardingClassPairs"
      vlan_priority_entries: 
        operations: "CRUD"
        collectionType: "map"
        description: "Map of .1p priority code to applicable forwarding class for packet."
        presence: "optional"
        wrapper: true
        mapKey: "key"
        $ref: "types.json#/definitions/QosIdForwardingClassPairs"
      default_forwarding_class_id: 
        operations: "CRUD"
        presence: "required"
        description: "Default forwarding class used for all non-specified QOS bits"
        $ref: "types.json#/definitions/ForwardingClassId"
      dscp_entries: 
        operations: "CRUD"
        collectionType: "map"
        description: "Map of DSCP match condition and applicable forwarding class for packet."
        presence: "optional"
        wrapper: true
        mapKey: "key"
        $ref: "types.json#/definitions/QosIdForwardingClassPairs"

