version: 2
jobs:
  build-job:
    working_directory: /go/src/github.com/Juniper/contrail
    docker:
      - image: circleci/golang:1.9.2
      - image: circleci/mysql:5.7
        environment:
          - MYSQL_ROOT_PASSWORD=contrail123
    steps:
    - checkout
    - run:
        name: install mysql client
        command: sudo apt install mysql-client
    - run:
        name: install deps
        command: ./tools/deps.sh
    - run:
        name: lint
        command: ./tools/lint.sh
    - run:
        name: Wait for db
        command: dockerize -wait tcp://localhost:3306 -timeout 1m
    - run:
        name: Reset database
        command: ./tools/reset_db.sh
    - run:
        name: Run Tesc
        command: make test
    # - run:
    #     name: coverall
    #     command: /go/bin/goveralls -coverprofile=profile.cov -service=circle-ci -repotoken=$COVERALLS_TOKEN
  deploy-job:
    docker:
      - image: circleci/golang:1.9
      - image: circleci/mysql:5.7
        environment:
          - MYSQL_ROOT_PASSWORD=contrail123
    working_directory: /go/src/github.com/Juniper/contrail
    steps:
    - checkout
    - run:
        name: install mysql client
        command: sudo apt install mysql-client
    - run:
        name: Wait for db
        command: dockerize -wait tcp://localhost:3306 -timeout 1m
    - run:
        name: Reset database
        command: ./tools/reset_db.sh
    - run:
        name: install packaging tools
        command: |
            sudo apt-get install -y zip build-essential rpm rubygems ruby-dev curl
            curl -L https://github.com/tcnksm/ghr/releases/download/v0.5.0/ghr_v0.5.0_linux_amd64.zip -o ghr_v0.5.0_linux_amd64.zip
            unzip ghr_v0.5.0_linux_amd64.zip
            chmod 0755 ghr
            make deps
    - run:
        name: install fpm
        command: sudo gem install --no-ri --no-rdoc fpm
    - run:
        name: Make package
        command: make package
    - run:
        name: Test package
        command: |
            sudo dpkg -i dist/contrail_0.0.1_amd64.deb
            contrail -h
            sudo service contrail start
            sleep 1
            curl http://localhost:9091/virtual-networks
    - run:
        name: Make binaries
        command: make binaries
    - run:
        name: Push to github
        command: ./ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME -replace pre-release dist/

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master