{% if input.AuthURL %}
id: {{ input.ID }}
password: {{ input.Password }}
{%if input.DomainID %}domain_id: {{ input.DomainID }}{%endif%}
{%if input.DomainName %}domain_Name: {{ input.DomainName }}{%endif%}
{%if input.ProjectID %}project_id: {{ input.ProjectID }}{%endif%}
{%if input.ProjectName %}project_name: {{ input.ProjectName }}{%endif%}
auth_url: {{ input.AuthURL }}
{% endif %}
endpoint: {{ input.Endpoint }}
insecure: {{ input.InSecure }}
resource_type: {{ resource.schema_id }}
resource_id: {{ resource.uuid }}
resource_action: {{ action }}
provisioner_type: {{ resource.ProvisionerType }}
log_level: debug
log_file: /var/log/contrail/deploy.log
template_root: /usr/share/contrail/templates/
service_user_id: {{ input.ServiceUserID }}
service_user_password: {{ input.ServiceUserPassword }}
dry_run: True

# Optional ansible params for dev/test
#ansible_sudo_pass: secret123
#ansible_fetch_url: https://review.opencontrail.org/Juniper/contrail-ansible-deployer refs/changes/80/40780/20
#ansible_cherry_pick_revision: FETCH_HEAD
#ansible_deployer_revision: GIT_COMMIT_HASH
