description: Contrail Config Node
extends:
- base
- has_status
id: contrail_config_node
metadata:
  category: cluster
references:
    node:
      operations: "CRUD"
      description: "Reference to node object for this config node."
      presence: "optional"
    rhospd_flavor:
      operations: "CRUD"
      description: "Reference to rhospd_flavor object for this config node."
      presence: "optional"
parents:
  contrail_cluster:
    operations: "CRUD"
    description: "Parent of this config node."
    presence: "optional"
plural: contrail_config_nodes
prefix: /
schema:
  properties:
    api_public_port:
      description: "Service listen port in the public/external network."
      default: 8082
      operations: CRUD
      presence: optional
      type: string
    api_private_port:
      description: "Service listen port in the private/internal network."
      default: 8082
      operations: CRUD
      presence: optional
      type: string
  propertiesOrder: []
  required: []
  type: object
singular: contrail_config_node
title: Contrail Config Node
type: ""
