- type: alltype
  template_path: model.tmpl
  output_path: pkg/models/gen_models.go
- type: all
  template_path: type_validation.tmpl
  output_path: pkg/models/gen_validation.go
- type: all
  template_path: cachedb.tmpl
  output_path: pkg/db/cache/gen_cache.go
- type: all
  template_path: event_encoding.tmpl
  output_path: pkg/services/gen_event_encoding.go
- type: all
  template_path: list_response_encoding.tmpl
  output_path: pkg/services/gen_list_response_encoding.go
- type: all
  template_path: sql_mysql.tmpl
  output_path: tools/init_mysql.sql
- type: all
  template_path: sql_psql.tmpl
  output_path: tools/init_psql.sql
- type: all
  template_path: sql_cleanup_mysql.tmpl
  output_path: tools/cleanup_mysql.sql
- type: all
  template_path: sql_cleanup_psql.tmpl
  output_path: tools/cleanup_psql.sql
- type: all
  template_path: db.tmpl
  output_path: pkg/db/gen_db.go
- type: all
  template_path: db_test.tmpl
  output_path: pkg/db/gen_db_test.go
- type: all
  template_path: db_common.tmpl
  output_path: pkg/db/gen_common.go
- type: all
  template_path: service_common.tmpl
  output_path: pkg/services/gen_common.go
- type: all
  template_path: service_interface.tmpl
  output_path: pkg/services/gen_service_interface.go
- type: all
  template_path: quota_checker.tmpl
  output_path: pkg/services/gen_quota_checker.go
- type: all
  template_path: sanitizer_service.tmpl
  output_path: pkg/services/gen_sanitizer.go
- type: all
  template_path: etcdserviceif.tmpl
  output_path: pkg/db/etcd/gen_etcd_notifier_service.go
- type: all
  template_path: vnc_api_notifier_service.tmpl
  output_path: pkg/services/vncapi/gen_notifier_service.go
- type: all
  template_path: compilationif.tmpl
  output_path: pkg/compilationif/gen_compilation.go
- type: all
  template_path: service.tmpl
  output_path: pkg/services/gen_service.go
- type: all
  template_path: proto_model.tmpl
  output_path: proto/__package__/pkg/models/generated.proto
- type: all
  template_path: proto_service.tmpl
  output_path: proto/__package__/pkg/services/generated.proto
- type: all
  template_path: client.tmpl
  output_path: pkg/apisrv/client/gen_http.go
