PATH_CONFIG:  /etc/multicloud
PATH_SSL_CONFIG_LOCAL: "~/.multicloud/ssl"
PATH_SSL_CONFIG: "{{ PATH_CONFIG }}/ssl"
PATH_OPENVPN_CONFIG: "{{ PATH_CONFIG }}/openvpn"
PATH_BIRD_CONFIG: "{{ PATH_CONFIG }}/bird"
PATH_STRONGSWAN_CONFIG: "{{ PATH_CONFIG }}/strongswan"
PATH_VRRP_CONFIG: "{{ PATH_CONFIG }}/vrrp"
PATH_AWS_CONFIG: "{{ PATH_CONFIG }}/aws"
PATH_INTERFACE_CONFIG: "/etc/network/interfaces.d"
PATH_FW_CONFIG: "{{ PATH_CONFIG }}/firewall"
PATH_GCP_CONFIG: "{{ PATH_CONFIG }}/gcp"
PATH_SECRET_CONFIG: "{{ PATH_CONFIG }}/secret"
PATH_VXLAN_CONFIG: "{{ PATH_CONFIG }}/vxlan"
CONTAINER_REGISTRY: test_registry
CONTRAIL_MULTICLOUD_VERSION: ocata-5.0-x
UPGRADE_KERNEL: False
KERNEL_VERSION: 3.10.0-862.11.6.el7.x86_64
AS: 65000
vpn_lo_network: 100.65.0.0/16
vpn_network: 100.64.0.0/16
openvpn_port: 443
bfd_interval: 200ms
bfd_multiplier: 5
bfd_interval_multihop: 500ms
bfd_multiplier_multihop: 5
core_bgp_secret: bgp_secret
