global_configuration:
  CONTAINER_REGISTRY: test_registry
  REGISTRY_PRIVATE_INSECURE: True
provider_config:
  bms:
    ssh_user: root
    ssh_pwd: c0ntrail123
    ntpserver: 10.1.1.100
instances:
  all_in_one_node:
    ip: 127.0.0.1
    ssh_user: test_ssh_user
    ssh_pwd: test_ssh_password
    ssh_public_key: test_ssh_key
    provider: bms
    roles:
      config:
      dhcp:
      config_database:
      control:
      webui:
      analytics:
      analytics_database:
      analytics_alarm:
      analytics_snmp:
      vrouter:
      openstack_control:
      openstack_network:
      openstack_storage:
      openstack_monitoring:
      openstack_compute:
contrail_configuration:
  CONTRAIL_VERSION: "ocata-5.0-x"
  CLOUD_ORCHESTRATOR: openstack
  RABBITMQ_NODE_PORT: 5673
  VROUTER_GATEWAY: 127.0.0.254
  ENCAP_PRIORITY: VXLAN,MPLSoUDP,MPLSoGRE
  OPENSTACK_VERSION: queens
  AUTH_MODE: keystone
  KEYSTONE_AUTH_HOST: 127.0.0.1
  KEYSTONE_AUTH_URL_VERSION: /v3
  CONTRAIL_CONTAINER_TAG: "master.100"
  GENERATE_SSH: True
  USE_OPENSTACK_TFTP: True
  CONTROL_NODES: 127.0.0.1
  WEBUI_NODES: 10.1.1.35
kolla_config:
  kolla_globals:
    enable_haproxy: no
  kolla_passwords:
    keystone_admin_password: contrail123
  customize:
    nova.conf: |
      [libvirt]
      virt_type=qemu
      cpu_mode=none
    swift-proxy-server/proxy-server.conf: |
      [filter:authtoken]
      service_token_roles_required = True
      service_token_roles = admin
