ansible/gateway/playbooks/deploy_and_run_all.yml:
  args: -i /tmp/contrail_cluster/test_cluster_uuid/multi-cloud/inventories/inventory.yml
ansible/contrail/playbooks/add_tunnel_routes.yml:
  args: -i /tmp/contrail_cluster/test_cluster_uuid/multi-cloud/inventories/inventory.yml --skip-tags remotegw
ansible/contrail/playbooks/configure.yml:
  args: -i /tmp/contrail_cluster/test_cluster_uuid/multi-cloud/inventories/inventory.yml
ansible/contrail/playbooks/orchestrator.yml:
  args: -i /tmp/contrail_cluster/test_cluster_uuid/multi-cloud/inventories/inventory.yml -e orchestrator=kubernetes
ansible/contrail/playbooks/deploy.yml:
  args: -i /tmp/contrail_cluster/test_cluster_uuid/multi-cloud/inventories/inventory.yml --skip-tags vrouter
ansible/contrail/playbooks/deploy.yml:
  args: -i /tmp/contrail_cluster/test_cluster_uuid/multi-cloud/inventories/inventory.yml --skip-tags config_database,config,control,webui,analytics,analytics_database,k8s
ansible/contrail/playbooks/add_tunnel_routes.yml:
  args: -i /tmp/contrail_cluster/test_cluster_uuid/multi-cloud/inventories/inventory.yml --skip-tags controllergw
ansible/contrail/playbooks/fix_compute_dns.yml:
  args: -i /tmp/contrail_cluster/test_cluster_uuid/multi-cloud/inventories/inventory.yml
