playbooks/provision_instances.yml:
  args: -i inventory/ -e config_file=/tmp/contrail_cluster/test_cluster_uuid/instances.yml -e orchestrator=kubernetes
playbooks/configure_instances.yml:
  args: -i inventory/ -e config_file=/tmp/contrail_cluster/test_cluster_uuid/instances.yml -e orchestrator=kubernetes
playbooks/install_k8s.yml:
  args: -i inventory/ -e config_file=/tmp/contrail_cluster/test_cluster_uuid/instances.yml -e orchestrator=kubernetes
playbooks/install_contrail.yml:
  args: -i inventory/ -e config_file=/tmp/contrail_cluster/test_cluster_uuid/instances.yml -e orchestrator=kubernetes
