global_configuration:
  CONTAINER_REGISTRY: opencontrailnightly
  REGISTRY_PRIVATE_INSECURE: false
provider_config:
  bms:
    ssh_user: root
    ssh_pwd: c0ntrail123
    ntpserver:
instances:
  xflow-node1:
    ip: 1.2.3.4
    provider: bms
    roles:
      appformix_flows:
        telemetry_in_band_interface_name: eth0
xflow_configuration:
  loadbalancer_collector_vip: 10.84.5.20
  kafka_volumes_host_path:
  clickhouse_volumes_host_path:
  kafka_replication_factor: 1
  clickhouse_replication_factor: 1
  xflow_base_distro: ubuntu
  keystone_username: admin
  keystone_domain_id: default
  appformix_auth_type: openstack
  docker_pull_images: false
  xflow_log_level: info
  kafka_flows_topic_retention_ms: 7200000
  apiserver_allowed_origins: ["*"]
  telemetry_in_band_cidr: 10.84.5.0/24
  loadbalancer_management_vip: 1.2.3.100
  telemetry_in_band_vlan_id: 128
